/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects. It is checked in
// here so the scaffold type-checks as soon as dependencies are installed.
